### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MK-NEUKO** [MK-NEUKO/Tic-Tac-Toe#1]
@suchja Hallo Jan,
kannst du noch einmal über meinen fertigen Quellcode gucken?
Als nächstes möchte ich das Spiel gern Objektorientiert umschreiben und noch ein paar Kleinigkeiten ändern, hinzufügen.
Dann würde ich gern wissen, ob man den content vom Lable auch mittig positionieren kann?
```HorizontalContentAlignment="Center"``` hat leider nicht funktioniert.
Kann man die Ecken des Label abrunden?
Kannst du es bitte auch mit in die Teilnehmerliste aufnehmen, ich habe an [dieser](https://github.com/LernMoment/tictactoe-wpf/issues/2) Stelle schon den Link hinterlassen.

**Comment by MK-NEUKO** [comment]
@suchja
Das Problem mit dem mittigen content liegt nicht im xaml-code. Höchstwahrscheinlich ist die Art und Weise, wie ich den String, der angezeigt wird, erzeuge bzw. verkette. 
```C#
MitteilungAnzeigen("Spieler \"O\" hat gewonnen !\nX = " + punkteX + " : " + punkteO + " = O");
```
Ich müsste den String so erzeugen, dass die zweite Zeile mittig unter die Erste kommt?

**Comment by suchja** [comment]
@MK-NEUKO 
Ich habe mir gerade nochmals deinen Quellcode angeschaut. Momentan würde ich ihn einfach erstmal so lassen. Die `for`-Schleife mit `switch-case` finde ich immer noch etwas verwirrend, aber das löst sich vielleicht auf, wenn du mehr in Richtung ObjektOrientierung gehst.

In meiner vorgeschlagenen Lösung zur Frage bezüglich der Zentrierung, habe ich dir auch eine Alternative für das Zusammensetzen der Mitteilung erstellt (siehe [hier](https://github.com/suchja/Tic-Tac-Toe/blob/ba29025082d9be0a8e53951a5adee9aeaa5f8150/TicTacToe/MainWindow.xaml.cs#L268)). Dieser Ansatz Werte in einen `string` einzufügen nennt sich "String-Interpolation". Mehr dazu findest du [hier](https://www.lernmoment.de/csharp-programmieren/mit-csharp-6-noch-mueheloser-werte-in-strings-einfuegen/).

Hast du schon eine Idee wie du das ganze in OO umsetzen willst?

**Comment by suchja** [comment]
@MK-NEUKO Link zu deinem Verzeichnis ist nun in der Teilnehmerliste. Ich dachte, ich hätte dich schon längst drin. Entschuldige!

**Comment by MK-NEUKO** [comment]
@suchja 
Vielen Dank für alles.
Funktioniert jetzt super, ich habe auch die Ecken rund bekommen.
Ich habe für das Label [**hier**](https://github.com/MK-NEUKO/Tic-Tac-Toe/blob/80804d92f38f769eb967313a180be86637d5a1f3/TicTacToe/MainWindow.xaml#L20) ein Style erstellt, dabei habe ich eineges über die WPF gelesen.
Das ist ein riesen Gebilde, jetzt weiß ich auch, warum mein WPF-Buch so dick ist.
Wegen OO kann ich bis jetzt nur sagen, eine Klasse für das Spielfeld, vielleicht mit dem Namen Spielfeld oder einfach nur TicTacToe. Und eine Klasse mit dem Namen Spieler. Das läuft parallel zu dem C# Kurs, in dem ich gerade beim MVC bin. Ich möchte dem Spiel Netzwerkfunktionalität geben, so das zwei Spieler über das Netzwerk spielen können. Das währe auch eine gute Übung, da heute fast alle Programme Netzwerkfunktionalität besitzen. System.Net.Sockets Namespace ist glaube ich die richtige Anlaufstelle.
Auch die Programmierung einer KI, könnte man hier Üben.

Eine kleine Anmerkung hätte ich noch, ich habe jetzt erst gesehen, dass in deinem Blog so viele Artikel über das Programmieren sind. Mir gefallen diese sehr, nur hätte ich sie nie an dieser Stelle vermutet. Ungeachtet meines Denkens, wo bestimmte Artikel zu finden sind, könnte ich mir gut vorstellen, wenn dort eine Übersicht wäre, nach Themen/Kategorien geordnet, ähnlich einem Inhaltsverzeichnis. Denn wenn man auch den Blog geht, ahnt man nicht, dass dort so viele Artikel versteckt sind. 

Ich werde an dieser Stelle ein Tag und ein Releas/pre Releas machen.
Ich werde mich in den nächsten Tagen / Wochen dann mit der OO des Spiels und dem C#-Kurs beschäftigen.

**Comment by suchja** [comment]
Ja, WPF ist wirklich sehr umfangreich. Daher ist es gut sich Stück für Stück einzuarbeiten. Es gibt sicherlich auch vieles das du erstmal gar nicht brauchst.

Vielen Dank für deine Rückmeldung zum Blog! Da gebe ich absolut recht. Der Plan ist, dass ich ein komplettes neues Design für LernMoment.de bekomme. Diesmal möchte ich das allerdings von einem Profi in dem Bereich machen lassen. Solange muss nun die unübersichtliche Version noch reichen.

Viel Spaß beim Kurs und bei der OO-Variante. Ich bin gespannt wie es dann aussieht.

**Comment by MK-NEUKO** [comment]
@suchja 
Ich habe lang überlegt wie ich es OO umsetzte, schließlich habe ich entschieden die aufwendige Variante umzusetzen. In meinem dicken C# Buch habe ich ein ganzes Kapitel MVVM, dieses werde ich durcharbeiten und gleichzeitig das gelernte auf Tic-Tac-Toe anzuwenden.
In der Readme in meinem Reposetory stehen alle Einzelheiten.

**Comment by MK-NEUKO** [comment]
@suchja 
Ich habe die letzten Tage erstmal am Design gearbeitet. 
So etwa wird es dann aussehen. 

![PSX_20200726_190702](https://user-images.githubusercontent.com/67154322/88485027-42f89f00-cf73-11ea-9931-584a7217334b.jpg)
