### ISSUE TITLE
Tic Tac Toe 1. Lernmail

### ISSUE THREAD

**Issue by MK-NEUKO** [MK-NEUKO/Tic-Tac-Toe#1]
@suchja
Wie angekündigt, der erste Teil.
Ich kann gleich weitermachen, die 2. mail habe ich ja schon.

**Comment by MK-NEUKO** [comment]
Die 2. LernMail ist abgearbeitet.

**Comment by MK-NEUKO** [comment]
Kann ich hier:
```xaml 
<Grid x:Name="spielfeld" ShowGridLines="True">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
```
das
```xaml 
ShowGridLines="True"
```
weglassen?
Ich hab mich gewundert, dass die gestrichelten Linien auch während der Laufzeit angezeigt werden.

**Comment by MK-NEUKO** [comment]
Ok, die letzte Frage hat sich auch erledigt.

**Comment by suchja** [comment]
Ja, kannst du 😁
